# Generated by Django 4.2.8 on 2023-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(max_length=500, upload_to='uploaded_pics/'),
        ),
    ]
